QakBot:
  author: Not Found
  description: QakBot Parser
  parsers:
  - .QakBot
Emotet:
  author: Not Found
  description: Emotet Parser
  parsers:
  - .Emotet
BitPaymer:
  author: Not Found
  description: BitPaymer Parser
  parsers:
  - .BitPaymer
Retefe:
  author: Not Found
  description: Retefe Parser
  parsers:
  - .Retefe
Zloader:
  author: Not Found
  description: Zloader Parser
  parsers:
  - .Zloader
Hancitor:
  author: Not Found
  description: Hancitor Parser
  parsers:
  - .Hancitor
IcedID:
  author: Not Found
  description: IcedID Parser
  parsers:
  - .IcedID
DoppelPaymer:
  author: Not Found
  description: DoppelPaymer Parser
  parsers:
  - .DoppelPaymer
HttpBrowser:
  author: Not Found
  description: HttpBrowser Parser
  parsers:
  - .HttpBrowser
EvilGrab:
  author: Not Found
  description: EvilGrab Parser
  parsers:
  - .evilgrab
DridexLoader:
  author: Not Found
  description: DridexLoader Parser
  parsers:
  - .DridexLoader
Loki:
  author: Not Found
  description: Loki Parser
  parsers:
  - .Loki
Remcos:
  author: Not Found
  description: Remcos Parser
  parsers:
  - .Remcos
BuerLoader:
  author: Not Found
  description: BuerLoader Parser
  parsers:
  - .BuerLoader
IcedIDStage1:
  author: Not Found
  description: IcedIDStage1 Parser
  parsers:
  - .IcedIDStage1
Redsip:
  author: Not Found
  description: Redsip Parser
  parsers:
  - .Redsip
ChChes:
  author: Not Found
  description: ChChes Parser
  parsers:
  - .ChChes
SmokeLoader:
  author: Not Found
  description: SmokeLoader Parser
  parsers:
  - .SmokeLoader
RedLeaf:
  author: Not Found
  description: RedLeaf Parser
  parsers:
  - .redleaf
RCSession:
  author: Not Found
  description: RCSession Parser
  parsers:
  - .RCSession
Enfal:
  author: Not Found
  description: Enfal Parser
  parsers:
  - .enfal
Azorult:
  author: Not Found
  description: Azorult Parser
  parsers:
  - .Azorult
IcedIDStage2:
  author: Not Found
  description: IcedIDStage2 Parser
  parsers:
  - .IcedIDStage2
