RedLeaf:
  author: Not Found
  description: RedLeaf Parser
  parsers:
  - .redleaf
Zloader:
  author: Not Found
  description: Zloader Parser
  parsers:
  - .Zloader
IcedIDStage2:
  author: Not Found
  description: IcedIDStage2 Parser
  parsers:
  - .IcedIDStage2
BitPaymer:
  author: Not Found
  description: BitPaymer Parser
  parsers:
  - .BitPaymer
DridexLoader:
  author: Not Found
  description: DridexLoader Parser
  parsers:
  - .DridexLoader
Remcos:
  author: Not Found
  description: Remcos Parser
  parsers:
  - .Remcos
ChChes:
  author: Not Found
  description: ChChes Parser
  parsers:
  - .ChChes
IcedIDStage1:
  author: Not Found
  description: IcedIDStage1 Parser
  parsers:
  - .IcedIDStage1
HttpBrowser:
  author: Not Found
  description: HttpBrowser Parser
  parsers:
  - .HttpBrowser
Redsip:
  author: Not Found
  description: Redsip Parser
  parsers:
  - .Redsip
IcedID:
  author: Not Found
  description: IcedID Parser
  parsers:
  - .IcedID
Hancitor:
  author: Not Found
  description: Hancitor Parser
  parsers:
  - .Hancitor
EvilGrab:
  author: Not Found
  description: EvilGrab Parser
  parsers:
  - .evilgrab
Loki:
  author: Not Found
  description: Loki Parser
  parsers:
  - .Loki
Retefe:
  author: Not Found
  description: Retefe Parser
  parsers:
  - .Retefe
Azorult:
  author: Not Found
  description: Azorult Parser
  parsers:
  - .Azorult
QakBot:
  author: Not Found
  description: QakBot Parser
  parsers:
  - .QakBot
DoppelPaymer:
  author: Not Found
  description: DoppelPaymer Parser
  parsers:
  - .DoppelPaymer
BuerLoader:
  author: Not Found
  description: BuerLoader Parser
  parsers:
  - .BuerLoader
SmokeLoader:
  author: Not Found
  description: SmokeLoader Parser
  parsers:
  - .SmokeLoader
Enfal:
  author: Not Found
  description: Enfal Parser
  parsers:
  - .enfal
RCSession:
  author: Not Found
  description: RCSession Parser
  parsers:
  - .RCSession
Emotet:
  author: Not Found
  description: Emotet Parser
  parsers:
  - .Emotet
