name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        python3_7:
          python.version: "3.7"
        Python3_8:
          python.version: "3.8"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - script: |
          install_path=`pwd`
          echo "Setup YARA"
          YARA_VERSION=4.1.0
          sudo apt-get update
          sudo apt-get install -y libfuzzy-dev git libssl1.1 libmagic1 libssl-dev libmagic-dev automake libtool make gcc wget git
          sudo rm -rf /var/lib/apt/lists/*
          wget -O /tmp/yara.tar.gz https://github.com/VirusTotal/yara/archive/v$YARA_VERSION.tar.gz
          tar -zxf /tmp/yara.tar.gz -C /tmp
          cd /tmp/yara-$YARA_VERSION
          ./bootstrap.sh
          ./configure --enable-cuckoo --enable-magic --enable-dotnet --with-crypto --prefix /tmp/yara_install
          make
          make install
          sudo cp -r /tmp/yara_install /usr/local
          cd $install_path
          echo "Install Python packages"
          sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir assemblyline assemblyline_v4_service magic-yara-python gitpython plyara pyparsing==2.3.0
          sudo env "PATH=$PATH" python -m pip install -U -r `pwd`/test/requirements.txt
          echo "Install ConfigExtractor"
          git clone --recurse-submodules https://github.com/CybercentreCanada/configextractor-py.git /tmp/configextractor-py
          sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir /tmp/configextractor-py/RATDecoders/ /tmp/configextractor-py/
          sudo mkdir /opt/al_service/
          echo "Cloning CAPE parsers and patch in library"
          git clone https://github.com/kevoreilly/CAPEv2.git /opt/al_service/CAPEv2
          sudo rm -f /opt/al_service/CAPEv2/modules/processing/parsers/CAPE/*.py_disabled
          sudo rm -f /opt/al_service/CAPEv2/modules/processing/parsers/CAPE/test_cape.py
          CAPE_PARSERS_DIR=/opt/al_service/CAPEv2/modules/processing/parsers/CAPE/
          PYTHONPATH=$PYTHONPATH:/opt/al_service/CAPEv2/
          sudo mv /tmp/configextractor-py/dependencies /opt/al_service/dependencies
          sudo rm -rf /tmp/* /var/lib/apt/lists/* ~/.cache/pip /tmp/configextractor-py/
        displayName: Setup environment
      - script: python -m pytest --durations=10 -rsx -vv --cov-report=xml --cov=configextractor
        displayName: Test
      - script: python -m codecov
        displayName: Upload Coverage
